services:
  postgres:
    image: postgres:17.4-alpine
    container_name: challenge-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h wronghost"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
